### PR TITLE
use Appveyor's Boost installation; closes #426

### LINKED ISSUE #426: Consider using Appveyor's Boost installation instead of "own" build
https://www.appveyor.com/docs/build-environment/#boost

### PR DESCRIPTION
**Pull request by bast**
In the hope that it will speed up builds and pass the CI.

### CODE REVIEW

**Comment by bast** [comment]
Nope. This is an incomplete PR - I need to rework this. MSYS did not find anything.

**Comment by robertodr** [comment]
I don't think MSYS can work with system Boost on Appveyor. I think those are geared towards VS, installing Boost for MSYS is relatively fast and doesn't blow up cache size. VcPkg on the other hand takes forever...

**Comment by bast** [comment]
Ah thanks for the comment - I will update the PR.

**Comment by bast** [comment]
VS not happy with 3/8 - I need to later look closer into it.

**Comment by robertodr** [comment]
Correction. Debug or release doesn't matter. It's shared vs static that matters: https://ci.appveyor.com/project/robertodr/appveyor-boost-cmake

**Comment by bast** [comment]
Overtaken by #436. Closing.

**Pull request closed without merging**
