### PR TITLE
Chapter 9 apply reviews

### PR DESCRIPTION
**Pull request by robertodr**
## Description
Cleans up code a bit and get testing on Appveyor up and running.
Code samples are in sync with TC, though Appveyor is still quite a bit in shambles and I can't exclude there will be some little tweaks here and there (though it actually seems unlikely)
~The history is also a mess, but I'll squash some of the intermediates.~

## Todos
  - [x] Simplify pybind11 recipe. It is now a bit more compact, uses imported target `pybind11::module` from a `find_package` call, and more closely resembles the superbuilds in chapter 8.
  - [x] Use `set_tests_properties` rather than `set_property`
  - [x] Code samples in sync with TC.

## Status

- [x]  Ready to go

### CODE REVIEW

**Comment by bast** [comment]
Thanks! Waiting for Appveyor and then we can merge.

**Comment by robertodr** [comment]
Have another look at recipe 1 (which was changed) I have kept the examples using UUID, but these are not discussed on TC.

**Comment by robertodr** [comment]
I'll pull this one in.

**Comment by bast** [comment]
Thanks! I like the new example.

**Pull request merged**
