### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by AxiosCros**
## Description

Fix spelling of `_bootstrap_select_libraries` variable

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by bast** [comment]
Thank you! Sorry for slow follow-up ... we need to reanimate the automated testing which will be few days of work. But your change is so "obvious" that we might merge it across the CI.

**Review by bast — APPROVED** [review]
Just grepped the project. Good catch! I see no reason not to merge. Thank you!

**Comment by bast** [comment]
Can you please do this step and then I can merge? https://github.com/dev-cafe/cmake-cookbook/pull/523/checks?check_run_id=1006564817

Thank you! Sorry for this extra step.

**Comment by AxiosCros** [comment]
> Can you please do this step and then I can merge? https://github.com/dev-cafe/cmake-cookbook/pull/523/checks?check_run_id=1006564817
> 
> Thank you! Sorry for this extra step.

ok. already done.

**Comment by bast** [comment]
Thank you!

**Pull request merged**
